apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "volunteer-to.fullname" . }}-api
  labels:
    {{ include "volunteer-to.metadataLabels" . | nindent 2 | trim }}
spec:
  selector:
    matchLabels:
      app: {{ template "volunteer-to.name" . }}
      instance: {{ .Release.Name }}
      role: api
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: {{ template "volunteer-to.name" . }}
      labels:
        {{ include "volunteer-to.metadataLabels" . | nindent 6 | trim }}
        role: api
    spec:
      serviceAccountName: {{ template "volunteer-to.fullname" . }}-api
      containers:
      - name: {{ template "volunteer-to.fullname" . }}
        image: {{ include "volunteer-to.api.image" . }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        env:
        {{- range $name, $value := .Values.devEnv }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
          - containerPort: {{ .Values.api.containerPort }}
            name: http
        resources:
          {{ toYaml .Values.api.resources | nindent 10 | trim }}
        volumeMounts:
          - mountPath: {{ .Values.sslCertPath }}
            name: aws-cert
      volumes:
        - name: aws-cert
          hostPath:
            path: {{ .Values.sslCertPath }}
