apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "volunteer-to.fullname" . }}-readonly
  labels:
    {{ include "volunteer-to.metadataLabels" . | nindent 2 | trim }}
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - pods
  verbs:
  - get
  - list
