apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "volunteer-to.fullname" . }}-db
  labels:
    {{ include "volunteer-to.metadataLabels" . | nindent 2 | trim }}
spec:
  selector:
    matchLabels:
      app: {{ template "volunteer-to.name" . }}
      instance: {{ .Release.Name }}
      role: db
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: {{ template "volunteer-to.name" . }}
      labels:
        {{ include "volunteer-to.metadataLabels" . | nindent 6 | trim }}
        role: db
    spec:
      containers:
        - name: {{ template "volunteer-to.fullname" . }}-db
          image: {{ include "volunteer-to.db.image" . }}
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          env:
          {{- range $name, $value := .Values.devEnv }}
            - name: {{ $name }}
              value: {{ $value | quote }}
          {{- end }}
          resources:
            {{ toYaml .Values.db.resources | nindent 10 | trim }}
          volumeMounts:
            - mountPath: {{ .Values.sslCertPath }}
              name: aws-cert
      volumes:
        - name: aws-cert
          hostPath:
            path: {{ .Values.sslCertPath }}
